name: conformal-trust
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ipykernel
  - pip
  - numpy
  - numpy-base
  - matplotlib
  - matplotlib-base
  - pandas
  - pyarrow
  - pyyaml
  - pytorch 
  - pytorch-cuda=12.1
  - torchvision
  - torchaudio 
  - requests
  - seaborn
  - scipy
  - scikit-learn
  - tqdm
  - faiss
  - faiss-gpu
  - pip:
      - cvxpy
      - mosek
      - statsmodels==0.14.2
